### PR TITLE
build: bump date-fns 4.1.0

### PR DESCRIPTION
**Pull request by obdulia-losantos**
Based on https://github.com/rsuite/rsuite/discussions/3602

### CODE REVIEW

**Comment by simonguo** [comment]
Hi @obdulia-losantos  thank you very much for your contribution! We have not upgraded the date-fns version, one of the reasons is that the latest version of date-fns will not support IE11, I may need some data to determine whether to abandon support for IE11.

**Comment by simonguo** [comment]
Hi @obdulia-losantos
rsuite will deprecate IE11 in v6 and plan to upgrade date-fns.
You can submit the date-fns upgrade PR to the [next branch](https://github.com/rsuite/rsuite/tree/next)

**Comment by simonguo** [comment]
change branch

**Comment by obdulia-losantos** [comment]
@simonguo You can check PR #4079.

**Pull request closed without merging**
