### PR TITLE
Implement an option for showing week numbers in the Datepickers

### PR DESCRIPTION
**Pull request by viart**
Covers both `<DatePicker />` & `<DateRangePicker />`

### CODE REVIEW

**Comment by simonguo** [comment]
Thank you very much for contributing the code, this is a great feature.

But there are two problems:
1. The style is different from what our designers demand, and there may be some minor adjustments.
2. We have now migrated from flow to typescript , which is great if you can contribute code related to typescript.
https://github.com/rsuite/rsuite/tree/typescript
https://github.com/rsuite/rsuite.github.io/tree/next

**Comment by viart** [comment]
@simonguo thanks
1. it looks nice, will try to cover it
2. sure, will update and PR to those branches

**Comment by viart** [comment]
@simonguo I see that in the TS version you have both TS interfaces on Props and `propTypes`, do you you really need them both? `propTypes` looks a bit redundant to me.

**Comment by simonguo** [comment]
@viart 
If the developer does not use TS, propTypes is necessary as a runtime check.
However, propTypes can be removed by `babel-plugin-transform-react-remove-prop-types` when the project is built and packaged.

**Comment by viart** [comment]
I see, will add them too

**Comment by viart** [comment]
Closed in favour of #526

**Pull request closed without merging**
