### PR TITLE
fix(DateRangePicker): fix month switching with the “show one calendar” property

### PR DESCRIPTION
**Pull request by xTrogwaRx**

### CODE REVIEW

**Review by simonguo — COMMENTED** [review]
Please describe in detail the exact issue you fixed. Also please add unit tests for the added code.

**Comment by xTrogwaRx** [comment]
> Please describe in detail the exact issue you fixed. Also please add unit tests for the added code.

If you set the showOneCalendar property in the DateRangePicker component, when you try to select a date in the current month, the calendar switches to the next month.

Expected behavior: the calendar stays on the same month, since the user may need to select a date in the current or previous months.

I unfortunately have never written tests, but I'll try to read about tests and try to add them in my spare time.

**Comment by simonguo** [comment]
Understood, this is indeed an issue that needs improvement

**Comment by simonguo** [comment]
Fixed in v5.72.0

**Pull request closed without merging**
