### PR TITLE
Create ne_NP.ts for Nepali Locale Support.

### PR DESCRIPTION
**Pull request by manojpudasaini**
locale for Nepali language added.

### CODE REVIEW

**Review by simonguo — CHANGES_REQUESTED** [review]
Hi, please export ne_NP in [index.ts](https://github.com/rsuite/rsuite/blob/main/src/locales/index.ts).

**Comment by manojpudasaini** [comment]
> Hi, please export ne_NP in [index.ts](https://github.com/rsuite/rsuite/blob/main/src/locales/index.ts).

Sure, I have exported ne_NP in index.ts and updated the pull request.

**Review by simonguo — APPROVED** [review]

**Comment by SevenOutman** [comment]
@manojpudasaini Thanks for contributing this edit!

**Comment by manojpudasaini** [comment]
> @manojpudasaini Thanks for contributing this edit!

Thank you, Glad to be contributing for what i love and prefer to use.

**Pull request merged**
