### PR TITLE
Fixed Triggering onSelect twice on Dropdown Menu

### PR DESCRIPTION
**Pull request by hassanzohdy**
The issue is `onSelect` is triggered twice.

```tsx
export default function Dropdown() {
  const handleSelect = (eventKey: any) => {
    console.log(eventKey);
  };
  return (
    <>
      <Dropdown.Menu onSelect={handleSelect}>
        <Dropdown.Item eventKey={3}>Download As...</Dropdown.Item>
        <Dropdown.Item eventKey={4}>Export PDF</Dropdown.Item>
        <Dropdown.Item eventKey={5}>Export HTML</Dropdown.Item>
        <Dropdown.Item eventKey={6}>Settings</Dropdown.Item>
        <Dropdown.Item eventKey={7}>About</Dropdown.Item>
      </Dropdown.Menu>
    </>
  );
}
```

Or Check the following Code Sandbox 

https://codesandbox.io/s/react-typescript-forked-iybjwt?file=/src/App.tsx

Click on any item on the dropdown then check the console log

### CODE REVIEW

**Review by SevenOutman — CHANGES_REQUESTED** [review]
Hi @hassanzohdy, please rebase this PR onto the latest `main` branch so that only topic-related commits are included.

**Comment by hassanzohdy** [comment]
@SevenOutman Already Updated it, only the fix is on the PR now.

**Comment by hassanzohdy** [comment]
@SevenOutman Can you give me a hint how to remove the old commits from this PR

Thanks

**Comment by SevenOutman** [comment]
> @SevenOutman Can you give me a hint how to remove the old commits from this PR
> 
> 
> 
> Thanks

You need to _rebase_ your branch onto the latest `main` branch, instead of _merge_ the `main` branch into your branch. Your branch was based on (checked out from) an older version of `main` branch, use `git rebase` command to re-base it onto the latest version of `main` branch.

FYI, to avoid opening a PR with outdated commits in the first place, you should always checkout a new branch from the latest `main` branch for each topic you want to contribute, instead of directly working on a branch that was for another topic.

**Pull request closed without merging**
