### PR TITLE
Create fr_FR.ts

### PR DESCRIPTION
**Pull request by kodsu**
Added french translations

### CODE REVIEW

**Review by simonguo — CHANGES_REQUESTED** [review]
@kodsu Thank you so much for adding the French translation. However, the following areas also need to be modified.

1.export fr_FR in index.ts
https://github.com/rsuite/rsuite/blob/main/src/locales/index.ts#L17-L18

2.Add French to the document
https://github.com/rsuite/rsuite/blob/main/docs/pages/guide/i18n/en-US/index.md

| Locale | Description         |
| ------ | ------------------- |
| fr_FR  | French |

https://github.com/rsuite/rsuite/blob/main/docs/pages/guide/i18n/zh-CN/index.md

| 语言名称 | 描述              |
| -------- | ----------------- |
| fr_FR    | 法语  |

**Comment by kodsu** [comment]
@simonguo Sorry I overlooked the requirements, now it should be okay hopefully.

**Review by simonguo — APPROVED** [review]

**Review by simonguo — CHANGES_REQUESTED** [review]
@kodsu  also need to update an example.
https://rsuite-nextjs-git-fork-kodsu-main-rsuite.vercel.app/guide/i18n/
image

example code https://github.com/rsuite/rsuite/blob/main/docs/pages/guide/i18n/fragments/example.md

**Comment by SevenOutman** [comment]
I think it's OK to merge this PR and we update the docs separately.

**Pull request merged**
