### PR TITLE
feat: formControl add valuePropName support

### PR DESCRIPTION
**Pull request by myNameIsDu**
formControl add valuePropName support

### CODE REVIEW

**Comment by simonguo** [comment]
Hi @myNameIsDu 
I'm not quite sure, what problem is it trying to solve?

**Comment by myNameIsDu** [comment]
> Hi @myNameIsDu I'm not quite sure, what problem is it trying to solve?

Here's an [example](https://codesandbox.io/s/unruffled-frost-vzyiit?file=/src/index.js)

The value of the Toggle component is actually checked,If I use it in a form, I have to wrap a layer, Others, such as Checkbox Component

**Comment by simonguo** [comment]
@myNameIsDu 
In use, I think the encapsulation of the Toggle component is easier to understand than the `valuePropName` prop.

**Comment by myNameIsDu** [comment]
> @myNameIsDu In use, I think the encapsulation of the Toggle component is easier to understand than the `valuePropName` prop.

Yeah,I think this is a very friendly prop for me,It can help me write lesser template code, And i think if one person knows how to wrap Toggle component, He must understand what this prop is doing

**Comment by SevenOutman** [comment]
I don't think a custom value prop is key to this `<Toggle>` case. We don't take `checked` from `<Toggle>` because it receives value via this "customized prop", but because *it's a checkbox*.

**Comment by myNameIsDu** [comment]
> I don't think a custom value prop is key to this `<Toggle>` case. We don't take `checked` from `<Toggle>` because it receives value via this "customized prop", but because _it's a checkbox_. The core of resolving this issue is to tell `<FormControl>` whether its accepter is a radio/checkbox or a normal textbox.

Yeah, if we can handle it internally that's the perfect situation

**Pull request closed without merging**
