### PR TITLE
fix(DatePicker): call onSelect when meridian toggled

### LINKED ISSUE #2906: [DatePicker] onSelect is not called when meridian toggled
### What version of rsuite are you using?

5.22.1

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.3.4

### What browser are you using?

Firefox

### Describe the Bug

Toggling the meridian (when time picker is shown with `showMeridian` set) does not trigger `onSelect`. To make the newly set value take effect either the time or date must be clicked.

### Expected Behavior

`onSelect` should fire when meridian is toggled.

### To Reproduce

_No response_

### PR DESCRIPTION
**Pull request by daggmano**
Fixes #2906

### CODE REVIEW

**Comment by daggmano** [comment]
Not sure where the conflicted file is coming from, `src/DatePicker/test/DatePickerSpec.js` doesn't exist in the repo. Please let me know if I need to do anything else.

**Comment by simonguo** [comment]
@daggmano The test files in the main branch have been refactored from js to tsx. You need to merge the main branch once to resolve the conflict.

**Comment by daggmano** [comment]
Thanks for that, I haven't needed to that across repos on GitHub before ;)

**Review by simonguo — APPROVED** [review]

**Comment by SevenOutman** [comment]
@daggmano Thanks!

**Pull request merged**
