### PR TITLE
feat: Reverse directional icons

### PR DESCRIPTION
**Pull request by MohammadYounes**

### CODE REVIEW

**Comment by simonguo** [comment]
The icon fix for dropdown is fine.
However, as to whether it is necessary to reverse `left` and `right`, I need to think about it again.

**Comment by hiyangguo** [comment]
@MohammadYounes Icon is not necessary to reverse directional .

**Comment by hiyangguo** [comment]
Relative #727

**Comment by MohammadYounes** [comment]
@hiyangguo Directional Icons do, for example:

* **LTR**
image

* **RTL**
image

**Comment by hiyangguo** [comment]
@MohammadYounes But sometimes you use icon  `left` mean is left rather than right. So  I think icon needn't reverse, right ?

**Comment by MohammadYounes** [comment]
@hiyangguo I believe having an icon that should be left in both LTR/RTL versions of the **same** app is highly unlikely. Most use cases are to indicate logical, rather than physical, direction. 

Why do you use a right pointing arrow for Next button? Because it's logical in LTR languages, where the future exists on the right. However, in RTL languages, it's the opposite, and the future exists on the left.

For example, see how Progress is affected by the language direction:

* **LTR**
image

* **RTL**
image

**Comment by hiyangguo** [comment]
@MohammadYounes Maybe you are right. Thank you very much.

**Pull request merged**
