### PR TITLE
Content property as shorthand to children

### PR DESCRIPTION
**Pull request by thing18**
allow to write code like <Button content='click me'/> instead of <Button>click me</Button>

### CODE REVIEW

**Comment by SevenOutman** [comment]
Hi @thing18, thanks for this edit. However the benefit in this edit prop doesn't look so obvious to me. Could you explain how it will make things easier than children?

**Comment by thing18** [comment]
allows writing lesser code, for example
<Button content='click me'/> instead of <Button>click me</Button>
in my opinion the first version is easier to write and to write, also is not a forced method, a developer can select either of versions.

**Comment by thing18** [comment]
allows writing lesser code, for example
`<Button content='click me/>` instead of `<Button>click me<Button/>`
in my opinion the first version is easier to write and to write, also is not a forced method, a developer can select either of versions.

**Comment by SevenOutman** [comment]
> <Button content='click me/> instead of <Button>click me<Button/>
> in my opinion the first version is easier to write and to write

I'm afraid the second way is more familiar and straightforward to most web developers as it resembles how HTML is composed.

>  also is not a forced method, a developer can select either of versions.

I don't think I see the necessity in adding this new prop that is identical to an existing prop. I would suggest you wrap your own Button (and other) component if you prefer attribute-ish style over children.

```jsx 
function MyButton({ content, children, ...props }) {
  return <Button {...props}>{content}</Button>;
}
```

**Pull request closed without merging**
