### PR TITLE
feat: added Japanese locale (ja_JP) 

### PR DESCRIPTION
**Pull request by PurpleMonkey729**
Add Japanese Locale.

### CODE REVIEW

**Review by simonguo — COMMENTED** [review]
Hi  Nishimura Hiroki

Please export `ja_JP` in [src/locales/index.ts](https://github.com/rsuite/rsuite/blob/main/src/locales/index.ts)

> refer to: https://github.com/rsuite/rsuite/pull/3075/files#diff-f8cd93b3865870e2172a474b69cbae7095bb09fc026c3e609bb20643ff164be1R10

**Comment by simonguo** [comment]
> my name is Yoshimura, not Nishimura.

Sorry, I mispronounced your name.

**Review by simonguo — APPROVED** [review]

**Comment by PurpleMonkey729** [comment]
Thanks @simongou

**Comment by AaPaul** [comment]
Hello @PurpleMonkey729,

Thank you for your help in adding Japanese support! I have one concern about the translation in Pagination.

The current translation is: `skip: '{0}に逝く'`. In English, `に逝く` is `pass away to` which is a polite expression for die. How about changing it to `skip: '{0}ページへ'`?

Thanks!

**Pull request merged**
