### PR TITLE
feat(DateRangePicker): supports placing predefined ranges on the left

### PR DESCRIPTION
**Pull request by simonguo**
```diff
<DateRangePicker
  ranges={[
    {
      label: 'Today',
      value: [new Date(), new Date()],
+     // Sets the position where the predefined range is displayed, the default is bottom.
+     // Only supported on DateRangePicker。
+     placement: 'left'
    }
  ]}
/>;
```
> https://rsuite-nextjs-git-feat-daterangepicker-rsuite.vercel.app/components/date-range-picker/#predefined-date-ranges

image

image

### CODE REVIEW

**Comment by SevenOutman** [comment]
Does this edit change the current appearance ("link"-like) of the shortcuts on the bottom toolbar?

**Comment by SevenOutman** [comment]
Does this edit change the current appearance ("link"-like) of the shortcuts on the bottom toolbar?

**Comment by SevenOutman** [comment]
Does this edit change the current appearance ("link"-like) of the shortcuts on the bottom toolbar?

**Comment by simonguo** [comment]
> Does this edit change the current appearance ("link"-like) of the shortcuts on the bottom toolbar?

The style of the bottom button was not changed. It was customized in this demo.

**Review by SevenOutman — APPROVED** [review]

**Pull request merged**
