### PR TITLE
fix(DatePicker): reset calendar selection after closing picker menu

### PR DESCRIPTION
**Pull request by SevenOutman**
Before

https://user-images.githubusercontent.com/8225666/195821138-17bca5a6-c3e7-4139-9f1b-41037a93a494.mov

After

https://user-images.githubusercontent.com/8225666/195821129-418a52b4-333b-4390-83b8-db6091552da4.mov

### CODE REVIEW

**Review by simonguo — CHANGES_REQUESTED** [review]
The active element of the calendar panel should not be reset after clicking the OK button to select a date.

https://rsuite-nextjs-git-fix-datepicker-reset-on-close-rsuite.vercel.app/components/date-picker/

https://user-images.githubusercontent.com/1203827/196313636-ac07a5a7-a894-4794-b253-38ee3a642303.mp4

**Comment by SevenOutman** [comment]
> The active element of the calendar panel should not be reset after clicking the OK button to select a date.

This issue does not seem to be caused by this PR, it's also reproducible with the production build https://rsuitejs.com/components/date-picker/#basic .

**Comment by simonguo** [comment]
> > The active element of the calendar panel should not be reset after clicking the OK button to select a date.
> 
> This issue does not seem to be caused by this PR, it's also reproducible with the production build https://rsuitejs.com/components/date-picker/#basic .

I tried it and the issue does not exist in the production build.

**Comment by SevenOutman** [comment]
It's fixed now

**Review by simonguo — APPROVED** [review]

**Pull request merged**
