### PR TITLE
feat(Next.js): add 'use client' to all components

### PR DESCRIPTION
**Pull request by psebestyen**
Added 'use client' to the index of all components to make them compatible with Next.js 13

### CODE REVIEW

**Comment by SevenOutman** [comment]
@psebestyen Thanks for contributing this edit!

Could you provide a working demo of Next.js 13 (RSC) using rsuite with this change?
You can install the package built from this PR by CodeSandbox with:

```shell
npm i https://pkg.csb.dev/rsuite/rsuite/commit/b9544eca/rsuite
```

**Comment by psebestyen** [comment]
Sorry for the delay with this. As I was trying to create a sample Nextjs 13 app I ran into some issues. Specifically, with nested components such as Nav.Item and Nav.Menu. The error I am getting is 

> Error: Unsupported Server Component type: undefined

This is the case even if I add 'use client' at the top of each individual component, not just to index.tsx. There is no obvious solution as far as I can tell but I don't know enough about Nextjs to be sure. Does anyone have any suggestions?

By the way, creating a sample Nextjs app is really simple with npx create-next-app@latest (use the app directory option) in case anybody wants to try.

**Comment by iska9der** [comment]
> Sorry for the delay with this. As I was trying to create a sample Nextjs 13 app I ran into some issues. Specifically, with nested components such as Nav.Item and Nav.Menu. The error I am getting is
> 
> > Error: Unsupported Server Component type: undefined

Try to add `'use client'` to `src/index.tsx`, maybe that would help

**Comment by iska9der** [comment]
@psebestyen 
After install package from this PR by [command](https://github.com/rsuite/rsuite/pull/3355#issuecomment-1702285565), 
and insert `'use client'` directly to `esm/index.js`, 
[Error: Unsupported Server Component type: undefined](https://github.com/rsuite/rsuite/pull/3355#issuecomment-1708278474)
is dissapeared, but im facing next issue
image

Found related issues:
[nextjs issue](https://github.com/vercel/next.js/issues/51593)
[antd faq](https://ant-design.antgroup.com/docs/react/faq#the-antd-component-reported-an-error-when-using-the-app-router-of-nextjs):

> At present, this problem is waiting for Next.js to give an official solution, before this, if you use sub-components in your page, you can try to add the following client tag at the top of the page to solve this problem

**Comment by MyNameIsTakenOMG** [comment]
Interesting, I didn't get any of this `sub-components` type of issue as @iska9der did when testing it in a code sandbox, or maybe I missed out something?🤔 Anyways, here are some screenshots below: 
Capture1
Capture2


As you can see, the version of `rsuite` that I got is from here: 

> @psebestyen Thanks for contributing this edit!
> 
> Could you provide a working demo of Next.js 13 (RSC) using rsuite with this change? You can install the package built from this PR by CodeSandbox with:
> 
> ```shell
> npm i https://pkg.csb.dev/rsuite/rsuite/commit/b9544eca/rsuite
> ```

**Comment by psebestyen** [comment]
If you have 'use client' at the top everything works fine. The idea was to be able to embed rsuite components in react server components, that is, no 'use client' at the top. To achieve this, I tried adding 'use client' in the rsuite components themselves (or index files) which works for most components (meaning I could embed them in server componets) but I was not able to do the same with these sub-components.

**Comment by simonguo** [comment]
@psebestyen  I will use a script to add 'use client' to each component. 

https://github.com/rsuite/rsuite/pull/3407

**Pull request closed without merging**
